# -*- coding: utf-8 -*-
"""LSTM_Fehlende Daten_Plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120dOZspBnOBl6fcTDZj2NOGYoJoaVFWs
"""

#Folgende Variablen werden benötigt:
#Modell A
#Mittelwert_A, ki90_A

#Modell B
#Mittelwert_B, ki90_B

#Modell C
#Mittelwert_C, ki90_C

models = {
    "Original": {
        "color": "#0072B2",   #Blau
        "hatch": "/"
    },
    "5 Jahre fehlen": {
        "color": "#E69F00",   #Orange
        "hatch": "\\"
    },
    "10 Jahre fehlen": {
        "color": "#CC79A7",   #Violett
        "hatch": "x"
    }
}

modelle = [
    ("Original",      Mittelwert_A, ki90_A),
    ("5 Jahre fehlen",Mittelwert_B, ki90_B),
    ("10 Jahre fehlen",Mittelwert_C, ki90_C),
]

plt.figure(figsize=(18, 12))

for i, feature in enumerate(Variablen):
    ax = plt.subplot(3, 1, i + 1)

    #Historische Daten

    ax.plot(
        Historie.index,
        Historie_inv[:, i],
        color="blue",
        linewidth=2,
        label="Historische Daten",
        zorder=3
    )

    #LSTM-MODELLE

    for label, mw, ki90 in modelle:
        color = models[label]["color"]
        hatch = models[label]["hatch"]

        #Mean
        ax.plot(
            x_Zukunft,
            mw[:, i],
            color=color,
            linewidth=3,
            label=f"{label} – Mean",
            zorder=5
        )


        ax.plot(
            x_Zukunft,
            ki90[0, :, i],
            color=color,
            linestyle="--",
            linewidth=2,
            label=f"{label} – KI unten",
            zorder=4
        )
        ax.plot(
            x_Zukunft,
            ki90[1, :, i],
            color=color,
            linestyle="--",
            linewidth=2,
            label=f"{label} – KI oben",
            zorder=4
        )


        ax.fill_between(
            x_Zukunft,
            ki90[0, :, i],
            ki90[1, :, i],
            color=color,
            alpha=0.12,
            hatch=hatch,
            linewidth=0,
            zorder=1
        )

    #Reale Werte

    ax.plot(
        x_Zukunft,
        Real[:, i],
        color="black",
        linestyle="--",
        linewidth=2.5,
        label="Reale Werte",
        zorder=6
    )

    ax.set_title(f"Vergleich der Modelle – {feature}", fontsize=13)
    ax.set_ylabel(f"{feature} [{Einheiten[feature]}]")
    ax.grid(True, alpha=0.3)
    ax.legend(ncol=3, fontsize=9)

for ax in plt.gcf().axes[:-1]:
    ax.tick_params(labelbottom=False)

plt.gcf().axes[-1].set_xlabel("Datum")

plt.tight_layout()
plt.show()