# -*- coding: utf-8 -*-
"""Lévy-driven OU-Prozess_Fehlende Daten_Plot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFrHjPJNidxMOsPglqP7Pf6j2BQs5knO
"""

#Folgende Variablen werden benötigt:
#Modell A
#sim_vol_A, sim_estr_A, sim_depo_A

#Modell B
#sim_vol_B, sim_estr_B, sim_depo_B

#Modell C
#sim_vol_C, sim_estr_C, sim_depo_C

# Mittelwert
Mittelwert_A = np.column_stack([
    sim_vol_A.mean(axis=0),
    sim_estr_A.mean(axis=0),
    sim_depo_A.mean(axis=0)
])

# 90%-KI
ki90_A = np.stack([
    np.percentile(sim_vol_A,  [5, 95], axis=0),
    np.percentile(sim_estr_A, [5, 95], axis=0),
    np.percentile(sim_depo_A, [5, 95], axis=0)
], axis=2)

# Mittelwert
Mittelwert_B = np.column_stack([
    sim_vol_B.mean(axis=0),
    sim_estr_B.mean(axis=0),
    sim_depo_B.mean(axis=0)
])

# 90%-KI
ki90_B = np.stack([
    np.percentile(sim_vol_B,  [5, 95], axis=0),
    np.percentile(sim_estr_B, [5, 95], axis=0),
    np.percentile(sim_depo_B, [5, 95], axis=0)
], axis=2)

# Mittelwert
Mittelwert_C = np.column_stack([
    sim_vol_C.mean(axis=0),
    sim_estr_C.mean(axis=0),
    sim_depo_C.mean(axis=0)
])

# 90%-KI
ki90_C = np.stack([
    np.percentile(sim_vol_C,  [5, 95], axis=0),
    np.percentile(sim_estr_C, [5, 95], axis=0),
    np.percentile(sim_depo_C, [5, 95], axis=0)
], axis=2)

Historie_OU = df.loc[HistorieAnfang:HistorieEnde]

models = {
    "Original": {
        "color": "#0072B2",   #Blau
        "hatch": "/"
    },
    "5 Jahre fehlen": {
        "color": "#E69F00",   #Orange
        "hatch": "\\"
    },
    "10 Jahre fehlen": {
        "color": "#CC79A7",   #Violett
        "hatch": "x"
    }
}

modelle = [
    ("Original",      Mittelwert_A, ki90_A),
    ("5 Jahre fehlen",Mittelwert_B, ki90_B),
    ("10 Jahre fehlen",Mittelwert_C, ki90_C),
]

plt.figure(figsize=(18, 12))

for i, feature in enumerate(Variablen):
    ax = plt.subplot(3, 1, i + 1)

    #Historische Daten

    ax.plot(
        Historie_OU.index,
        Historie_OU[feature].values,
        color="blue",
        linewidth=2,
        label="Historische Daten",
        zorder=3
    )

    for label, mw, ki90 in modelle:
        color = models[label]["color"]
        hatch = models[label]["hatch"]

        ax.plot(
            Zukunft,
            mw[:, i],
            color=color,
            linewidth=3,
            label=f"{label} – Mean",
            zorder=5
        )


        ax.plot(
            Zukunft,
            ki90[0, :, i],
            color=color,
            linestyle="--",
            linewidth=2,
            label=f"{label} – KI unten",
            zorder=4
        )
        ax.plot(
            Zukunft,
            ki90[1, :, i],
            color=color,
            linestyle="--",
            linewidth=2,
            label=f"{label} – KI oben",
            zorder=4
        )


        ax.fill_between(
            Zukunft,
            ki90[0, :, i],
            ki90[1, :, i],
            color=color,
            alpha=0.12,
            hatch=hatch,
            linewidth=0,
            zorder=1
        )

    #Reale Werte

    ax.plot(
        df_fut["Datum"],
        df_fut[feature].values,
        color="black",
        linestyle="--",
        linewidth=2.5,
        label="Reale Werte",
        zorder=6
    )

    ax.set_title(f"Vergleich der Modelle – {feature}", fontsize=13)
    ax.set_ylabel(f"{feature} [{Einheiten[feature]}]")
    ax.grid(True, alpha=0.3)
    ax.legend(ncol=3, fontsize=9)

for ax in plt.gcf().axes[:-1]:
    ax.tick_params(labelbottom=False)

plt.gcf().axes[-1].set_xlabel("Datum")

plt.tight_layout()
plt.show()