# -*- coding: utf-8 -*-
"""Vergleichsplot LSTM_Levy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zt1bynrNchT9xlO57ieYhsu8g0Ozykms
"""

ki90_lstm = []
ki98_lstm = []

for i in range(3):
    ki90_lstm.append(
        np.percentile(Vorhersagen[:, :, i], [5, 95], axis=0)
    )
    ki98_lstm.append(
        np.percentile(Vorhersagen[:, :, i], [1, 99], axis=0)
    )

#gemeinsame y-achse
def compute_y_limits(hist, lstm_sim, ou_sim, pad=0.05):
    vals = [
        hist.values,
        np.percentile(lstm_sim, [1, 99]),
        np.percentile(ou_sim,   [1, 99])
    ]
    vals = np.concatenate([v.ravel() for v in vals])
    lo, hi = vals.min(), vals.max()
    span = hi - lo
    return lo - pad * span, hi + pad * span


fig, axes = plt.subplots(3, 2, figsize=(18, 12), sharex=True)

features = [
    ("Einlagevolumen", "Mrd. €", sim_vol),
    ("€STR", "%", sim_estr),
    ("Einlagezinssatz", "%", sim_depo)
]

for i, (name, unit, ou_sim) in enumerate(features):

    y_lo, y_hi = compute_y_limits(
        Historie[name],
        Vorhersagen[:, :, i],
        ou_sim
    )

    #LSTM (links)

    ax = axes[i, 0]

    ki90 = np.percentile(Vorhersagen[:, :, i], [5, 95], axis=0)
    ki98 = np.percentile(Vorhersagen[:, :, i], [1, 99], axis=0)

    ax.plot(Historie.index, Historie[name], color="blue", lw=2)
    ax.plot(x_Zukunft, Mittelwert[:, i], color="red", lw=2)
    ax.fill_between(x_Zukunft, ki90[0], ki90[1], color="blue", alpha=0.30)
    ax.fill_between(x_Zukunft, ki98[0], ki98[1], color="blue", alpha=0.15)
    ax.plot(x_Zukunft, Real[:, i], "--", color="black", lw=2)

    ax.set_ylim(y_lo, y_hi)
    ax.set_title(f"LSTM – {name}")
    ax.set_ylabel(f"{name} [{unit}]")
    ax.grid(True)
    ax.legend(
    ["Historische Daten", "Vorhersage (MW)", "90%-KI", "98%-KI", "Reale Werte"]
    )


    #OU (rechts)

    ax = axes[i, 1]

    mw   = ou_sim.mean(axis=0)
    ki90 = np.percentile(ou_sim, [5, 95], axis=0)
    ki98 = np.percentile(ou_sim, [1, 99], axis=0)

    ax.plot(Historie.index, Historie[name], color="blue", lw=2)
    ax.plot(Zukunft, mw, color="red", lw=2)
    ax.fill_between(Zukunft, ki90[0], ki90[1], color="blue", alpha=0.30)
    ax.fill_between(Zukunft, ki98[0], ki98[1], color="blue", alpha=0.15)
    ax.plot(df_fut["Datum"], df_fut[name], "--", color="black", lw=2)

    ax.set_ylim(y_lo, y_hi)
    ax.set_title(f"Lévy-driven OU – {name}")
    ax.grid(True)
    ax.legend(
        ["Historische Daten", "Vorhersage (MW)", "90%-KI", "98%-KI", "Reale Werte"]
    )


#X-Achse nur unten

for ax in axes[:-1, :].flat:
    ax.tick_params(axis="x", which="both", labelbottom=False)


for ax in axes[-1, :]:
    ax.set_xlabel("Datum")

plt.tight_layout()
plt.show()