# -*- coding: utf-8 -*-
"""Vergleichsplot Levy_Levy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T6-7-gZ1OFltD2MCXqI0ZEL3JjKDNQ2M
"""

#Folgende Varibalen werden benötigt:
#Modell A
#sim_vol_A, sim_estr_A, sim_depo_A, Historie_A, Zukunft_A, df_fut_A

#Modell B
#sim_vol_B, sim_estr_B, sim_depo_B, Historie_B, Zukunft_B, df_fut_B

#gemeinsame y-achse
def compute_y_limits(hist, sim_A, sim_B, pad=0.05):
    vals = [
        hist.values,
        np.percentile(sim_A, [1, 99]),
        np.percentile(sim_B, [1, 99])
    ]
    vals = np.concatenate([v.ravel() for v in vals])
    lo, hi = vals.min(), vals.max()
    span = hi - lo
    return lo - pad * span, hi + pad * span


fig, axes = plt.subplots(3, 2, figsize=(18, 12), sharex=True)

features = [
    ("Einlagevolumen", "Mrd. €", sim_vol_A, sim_vol_B),
    ("€STR", "%", sim_estr_A, sim_estr_B),
    ("Einlagezinssatz", "%", sim_depo_A, sim_depo_B)
]

for i, (name, unit, sim_A, sim_B) in enumerate(features):

    y_lo, y_hi = compute_y_limits(
        Historie[name],
        sim_A,
        sim_B
    )

    #Lévy-driven OU-Prozess A

    ax = axes[i, 0]

    mw  = sim_A.mean(axis=0)
    ki90 = np.percentile(sim_A, [5, 95], axis=0)
    ki98 = np.percentile(sim_A, [1, 99], axis=0)

    ax.plot(Historie_A.index, Historie_A[name], color="blue", lw=2)
    ax.plot(Zukunft_A, mw, color="red", lw=2)
    ax.fill_between(Zukunft_A, ki90[0], ki90[1], color="blue", alpha=0.30)
    ax.fill_between(Zukunft_A, ki98[0], ki98[1], color="blue", alpha=0.15)
    ax.plot(df_fut_A["Datum"], df_fut_A[name], "--", color="black", lw=2)

    ax.set_ylim(y_lo, y_hi)
    ax.set_title(f"Lévy-driven OU-Prozess A– {name}")
    ax.set_ylabel(f"{name} [{unit}]")
    ax.grid(True)
    ax.legend(
    ["Historische Daten", "Vorhersage (MW)", "90%-KI", "98%-KI", "Reale Werte"]
    )

    #Lévy-driven OU-Prozess B

    ax = axes[i, 1]

    mw  = sim_B.mean(axis=0)
    ki90 = np.percentile(sim_B, [5, 95], axis=0)
    ki98 = np.percentile(sim_B, [1, 99], axis=0)

    ax.plot(Historie_B.index, Historie_B[name], color="blue", lw=2)
    ax.plot(Zukunft_B, mw, color="red", lw=2)
    ax.fill_between(Zukunft_B, ki90[0], ki90[1], color="blue", alpha=0.30)
    ax.fill_between(Zukunft_B, ki98[0], ki98[1], color="blue", alpha=0.15)
    ax.plot(df_fut_B["Datum"], df_fut_B[name], "--", color="black", lw=2)

    ax.set_ylim(y_lo, y_hi)
    ax.set_title(f"Lévy-driven OU-Prozess B – {name}")
    ax.grid(True)
    ax.legend(
    ["Historische Daten", "Vorhersage (MW)", "90%-KI", "98%-KI", "Reale Werte"]
    )

#X-Achse nur unten

for ax in axes[:-1, :].flat:
    ax.tick_params(axis="x", which="both", labelbottom=False)


for ax in axes[-1, :]:
    ax.set_xlabel("Datum")

plt.tight_layout()
plt.show()