# -*- coding: utf-8 -*-
"""Vergleichsplot LSTM_LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gucWJaO-AMgYc8-ltaz5vJ398MEl1Gsr
"""

#Folgende Variablen werden benötigt:
#Modell A
#Vorhersagen_A, Mittelwert_A, Real_A, x_Zukunft_A, Historie_A

#Modell B
#Vorhersagen_B, Mittelwert_B, Real_B, x_Zukunft_B, Historie_B

ki90_lstm = []
ki98_lstm = []

for i in range(3):
    ki90_lstm.append(
        np.percentile(Vorhersagen[:, :, i], [5, 95], axis=0)
    )
    ki98_lstm.append(
        np.percentile(Vorhersagen[:, :, i], [1, 99], axis=0)
    )

#gemeinsame y-achse
def compute_y_limits(hist, lstm_A, lstm_B, pad=0.05):
    vals = [
        hist.values,
        np.percentile(lstm_A, [1, 99]),
        np.percentile(lstm_B, [1, 99])
    ]
    vals = np.concatenate([v.ravel() for v in vals])
    lo, hi = vals.min(), vals.max()
    span = hi - lo
    return lo - pad * span, hi + pad * span


fig, axes = plt.subplots(3, 2, figsize=(18, 12), sharex=True)

features = [
    ("Einlagevolumen", "Mrd. €"),
    ("€STR", "%"),
    ("Einlagezinssatz", "%")
]


for i, (name, unit) in enumerate(features):

    y_lo, y_hi = compute_y_limits(
        Historie_A[name],
        Vorhersagen_A[:, :, i],
        Vorhersagen_B[:, :, i]
    )

    #LSTM A

    ax = axes[i, 0]

    ki90 = np.percentile(Vorhersagen_A[:, :, i], [5, 95], axis=0)
    ki98 = np.percentile(Vorhersagen_A[:, :, i], [1, 99], axis=0)

    ax.plot(Historie_A.index, Historie_A[name], color="blue", lw=2)
    ax.plot(x_Zukunft_A, Mittelwert_A[:, i], color="red", lw=2)
    ax.fill_between(x_Zukunft_A, ki90[0], ki90[1], color="blue", alpha=0.30)
    ax.fill_between(x_Zukunft_A, ki98[0], ki98[1], color="blue", alpha=0.15)
    ax.plot(x_Zukunft_A, Real_A[:, i], "--", color="black", lw=2)

    ax.set_ylim(y_lo, y_hi)
    ax.set_title(f"LSTM A – {name}")
    ax.set_ylabel(f"{name} [{unit}]")
    ax.grid(True)
    ax.legend(
    ["Historische Daten", "Vorhersage (MW)", "90%-KI", "98%-KI", "Reale Werte"]
    )

    #LSTM B

    ax = axes[i, 1]

    ki90 = np.percentile(Vorhersagen_B[:, :, i], [5, 95], axis=0)
    ki98 = np.percentile(Vorhersagen_B[:, :, i], [1, 99], axis=0)

    ax.plot(Historie_B.index, Historie_B[name], color="blue", lw=2)
    ax.plot(x_Zukunft_B, Mittelwert_B[:, i], color="red", lw=2)
    ax.fill_between(x_Zukunft_B, ki90[0], ki90[1], color="blue", alpha=0.30)
    ax.fill_between(x_Zukunft_B, ki98[0], ki98[1], color="blue", alpha=0.15)
    ax.plot(x_Zukunft_B, Real_B[:, i], "--", color="black", lw=2)

    ax.set_ylim(y_lo, y_hi)
    ax.set_title(f"LSTM B – {name}")
    ax.grid(True)
    ax.legend(
    ["Historische Daten", "Vorhersage (MW)", "90%-KI", "98%-KI", "Reale Werte"]
    )


#X-Achse nur unten

for ax in axes[:-1, :].flat:
    ax.tick_params(axis="x", which="both", labelbottom=False)


for ax in axes[-1, :]:
    ax.set_xlabel("Datum")

plt.tight_layout()
plt.show()