# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dt8nobaToU5n30lOHGwtWHo1227dS0q0
"""

# ==============================================================================
# 1. REQUIRED LIBRARIES & CONFIGURATION
# ==============================================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, r2_score
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from tqdm import tqdm  # <-- PROGRESS BAR LIBRARY
import os

# Filename for the directly uploaded Excel file
Daten = "Data all variables.xlsx"

if not os.path.exists(Daten):
    raise FileNotFoundError("ERROR: File not found! Please drag and drop 'Data all variables.xlsx' into the left-side Files panel!")

# Feature columns matching the XGBoost setup exactly
Variablen = ["Einlagevolumen", "€STR", "Einlagezinssatz", "GPRC_DEU", "MoM Inflation", "DAX", "10Y Bond"]

Gedächtnis = 100         # Lookback window (History length)
Prognosehorizont = 100   # Forecasting horizon (Future length)
Epochs = 60              # Number of training epochs per model
Batch_Size = 32
Learning_Rate = 0.001

# Time-series split points (Aligned with the teammate's setup)
TrainingEnde = "2023-11-30"
InputAnfang = "2023-12-01"
HistorieAnfang, HistorieEnde = "2023-06-01", "2023-11-30"

# List of models to execute sequentially
MODELS_TO_RUN = ["LSTM", "GRU", "CNN"]

# ==============================================================================
# 2. DATA PREPARATION
# ==============================================================================
df = pd.read_excel(Daten)
df["Datum"] = pd.to_datetime(df["Datum"])
df = df.sort_values("Datum").set_index("Datum")
df = df[Variablen]

# Stationarity step: Target the differences (volume changes) instead of absolute levels
df['Diff_Volume'] = df['Einlagevolumen'].diff()
df_clean = df.dropna()

# Feature scaling (0 to 1 normalization)
scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()

X_data = scaler_X.fit_transform(df_clean[Variablen].values)
y_data = scaler_y.fit_transform(df_clean[['Diff_Volume']].values)

# Generating 3D sequences required for neural networks
def create_sequences(X_arr, y_arr, gd, hz):
    X_seq, y_seq = [], []
    for i in range(len(X_arr) - gd - hz + 1):
        X_seq.append(X_arr[i : i + gd])
        y_seq.append(y_arr[i + gd : i + gd + hz].flatten())
    return np.array(X_seq), np.array(y_seq)

X_seq, y_seq = create_sequences(X_data, y_data, Gedächtnis, Prognosehorizont)

# Temporal train/test split based on predefined dates
split_idx = df_clean.index.get_loc(TrainingEnde) - Gedächtnis
X_train_np, y_train_np = X_seq[:split_idx], y_seq[:split_idx]

# Conversion to PyTorch Tensors
X_train_t = torch.tensor(X_train_np, dtype=torch.float32)
y_train_t = torch.tensor(y_train_np, dtype=torch.float32)

dataset = TensorDataset(X_train_t, y_train_t)
train_loader = DataLoader(dataset, batch_size=Batch_Size, shuffle=True)

# ==============================================================================
# 3. FLEXIBLE NEURAL NETWORK ARCHITECTURE
# ==============================================================================
class FlexibleVolumeNet(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, model_type="LSTM"):
        super(FlexibleVolumeNet, self).__init__()
        self.model_type = model_type

        if model_type == "LSTM":
            self.rnn = nn.LSTM(input_size, hidden_size, batch_first=True, num_layers=2)
            self.fc = nn.Linear(hidden_size, output_size)
        elif model_type == "GRU":
            self.rnn = nn.GRU(input_size, hidden_size, batch_first=True, num_layers=2)
            self.fc = nn.Linear(hidden_size, output_size)
        elif model_type == "CNN":
            # 1D Convolution for temporal pattern extraction
            self.conv1 = nn.Conv1d(in_channels=input_size, out_channels=32, kernel_size=3, padding=1)
            self.conv2 = nn.Conv1d(in_channels=32, out_channels=64, kernel_size=3, padding=1)
            self.pool = nn.AdaptiveAvgPool1d(1)
            self.fc = nn.Linear(64, output_size)

    def forward(self, x):
        if self.model_type in ["LSTM", "GRU"]:
            out, _ = self.rnn(x)
            return self.fc(out[:, -1, :]) # Projecting the last hidden state into the future
        elif self.model_type == "CNN":
            x = x.transpose(1, 2) # Transpose dimensions to fit PyTorch Conv1d format
            x = torch.relu(self.conv1(x))
            x = torch.relu(self.conv2(x))
            x = self.pool(x).squeeze(-1)
            return self.fc(x)

# Dictionaries to store evaluation metrics and predictions
saved_predictions = {}
metrics_report = []

# Extract ground truth test values for validation (computed once)
real_start_idx = df.index.get_loc(InputAnfang)
real_values = df.iloc[real_start_idx : real_start_idx + Prognosehorizont, 0].values

# ==============================================================================
# 4. SEQUENTIAL TRAINING LOOP FOR ALL ENSEMBLE MODELS
# ==============================================================================
for m_type in MODELS_TO_RUN:
    print("\n" + "="*50)
    print(f"-> TRAINING MODEL: {m_type} STARTED...")
    print("="*50)

    # Model instantiation, loss definition, and optimizer configuration
    model = FlexibleVolumeNet(input_size=len(Variablen), hidden_size=64, output_size=Prognosehorizont, model_type=m_type)
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=Learning_Rate)

    # Training phase with visual progress bar
    model.train()

    # tqdm wrapper adds the visual loading bar to the training loop
    with tqdm(total=Epochs, desc=f"Training {m_type}", unit="epoch") as pbar:
        for epoch in range(Epochs):
            epoch_loss = 0
            for batch_X, batch_y in train_loader:
                optimizer.zero_grad()
                predictions = model(batch_X)
                loss = criterion(predictions, batch_y)
                loss.backward()
                optimizer.step()
                epoch_loss += loss.item()

            # Update the progress bar and display the latest loss dynamically
            pbar.set_postfix({"Loss": f"{epoch_loss/len(train_loader):.5f}"})
            pbar.update(1)

    # Inference phase & Level reconstruction
    model.eval()
    input_idx = df_clean.index.get_loc(TrainingEnde)
    x_input_np = X_data[input_idx - Gedächtnis : input_idx].reshape(1, Gedächtnis, len(Variablen))
    x_input_t = torch.tensor(x_input_np, dtype=torch.float32)

    with torch.no_grad():
        raw_diff_pred = model(x_input_t).numpy().reshape(Prognosehorizont, 1)

    inv_diff_pred = scaler_y.inverse_transform(raw_diff_pred).flatten()

    # Mathematical reconstruction: Level = Last Known Level + Cumulative Sum of predicted changes
    last_actual_level = df.loc[TrainingEnde, "Einlagevolumen"]
    reconstructed_volume = last_actual_level + np.cumsum(inv_diff_pred)

    # Store predictions for plotting
    saved_predictions[m_type] = reconstructed_volume

    # Performance evaluation
    mae = mean_absolute_error(real_values, reconstructed_volume)
    r2 = r2_score(real_values, reconstructed_volume)
    metrics_report.append({"Model": m_type, "MAE (Billion €)": f"{mae:.2f}", "R2 Score": f"{r2:.4f}"})

# ==============================================================================
# 5. COMPREHENSIVE PERFORMANCE REPORT
# ==============================================================================
print("\n" + "═"*50)
print("              EVALUATION REPORT Summary")
print("═"*50)
metrics_df = pd.DataFrame(metrics_report)
print(metrics_df.to_string(index=False))
print("═"*50)

# ==============================================================================
# 6. COMPARATIVE SCIENTIFIC PLOT
# ==============================================================================
Historie = df.loc[HistorieAnfang:HistorieEnde, "Einlagevolumen"]
x_Zukunft = pd.date_range(InputAnfang, periods=Prognosehorizont, freq="D")

plt.figure(figsize=(15, 8))

# Plot baseline ground truth data
plt.plot(Historie.index, Historie.values, color="blue", label="Historical Data (Training)", linewidth=2)
plt.plot(x_Zukunft, real_values[:len(x_Zukunft)], "--", color="black", label="Actual Real Values (Test Target)", linewidth=2)

# Plot each deep learning model prediction with specific colors
colors = {"LSTM": "darkgreen", "GRU": "orangered", "CNN": "purple"}
for m_type in MODELS_TO_RUN:
    plt.plot(x_Zukunft, saved_predictions[m_type], color=colors[m_type], label=f"PyTorch {m_type} Forecast", linewidth=2)

plt.title("Master Thesis: Comparative Forecast Analysis of Deep Learning Architectures", fontsize=14)
plt.ylabel("Deposit Volume [Billion €]")
plt.xlabel("Date")
plt.grid(True, alpha=0.3)
plt.legend(loc="upper left")
plt.tight_layout()
plt.show()