# -*- coding: utf-8 -*-
"""Normalverteilt vs. NIG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1duCeicfP4SLPIBvc_Fpcuoi8IIVHRlRB
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import tensorflow_probability as tfp
from scipy.stats import norm

tfd = tfp.distributions

x = np.linspace(-6, 6, 1200).astype(np.float32)


#Normalverteilung

mu = 0.0
sigma = 1.0
pdf_norm = norm.pdf(x, loc=mu, scale=sigma)


#NIG-Verteilungen
#1)
alpha_1 = 3
beta_1  = 0.0
delta_1 = 1
dist_nig_1 = tfd.NormalInverseGaussian(
    loc=mu,
    scale=delta_1,
    tailweight=alpha_1,
    skewness=beta_1
)
pdf_nig_1 = dist_nig_1.prob(x).numpy()

#2)
alpha_2 = 3.0
beta_2  = 2.0
delta_2 = 1.0
dist_nig_2 = tfd.NormalInverseGaussian(
    loc=mu,
    scale=delta_2,
    tailweight=alpha_2,
    skewness=beta_2
)
pdf_nig_2 = dist_nig_2.prob(x).numpy()

#3)
alpha_3 = 1.0
beta_3  = 0.0
delta_3 = 3.0
dist_nig_3 = tfd.NormalInverseGaussian(
    loc=mu,
    scale=delta_3,
    tailweight=alpha_3,
    skewness=beta_3
)
pdf_nig_3 = dist_nig_3.prob(x).numpy()


#Plot

plt.figure(figsize=(9, 5))

plt.plot(x, pdf_norm, linestyle="--", linewidth=2,
         label="Standardnormalverteilung")

plt.plot(x, pdf_nig_1, linewidth=2,
         label="NIG: Dünne Tails (α=3, β=0, δ=1)")

plt.plot(x, pdf_nig_2, linewidth=2,
         label="NIG: schief (α=3, β=2, δ=1)")

plt.plot(x, pdf_nig_3, linewidth=2,
         label="NIG: schwere Tails (α=1, β=0, δ=3)")

plt.xlabel("x")
plt.ylabel("Dichte")
plt.legend()
plt.grid(True)

plt.show()