# -*- coding: utf-8 -*-
"""Ornstein-Uhlenbeck vs. Wiener.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFYtSLcNYzZk7LUY5XpiS5l53dp-oOkE
"""

import numpy as np
import matplotlib.pyplot as plt


#Parameter

T = 10.0
N = 1000
dt = T / N
t = np.linspace(0, T, N + 1)

n_paths = 20

kappa = 1.0
theta = 0.0
sigma = 1.0

#Zufallsinkremente

dW = np.sqrt(dt) * np.random.randn(n_paths, N)

#Wiener-Prozess

W = np.zeros((n_paths, N + 1))
for i in range(N):
    W[:, i + 1] = W[:, i] + sigma * dW[:, i]

#Ornstein–Uhlenbeck-Prozess

OU = np.zeros((n_paths, N + 1))
for i in range(N):
    OU[:, i + 1] = (
        OU[:, i]
        + kappa * (theta - OU[:, i]) * dt
        + sigma * dW[:, i]
    )

#Plot

plt.figure(figsize=(10, 5))

for i in range(n_paths):
    plt.plot(t, W[i], color="red", alpha=0.7, linewidth=1)
    plt.plot(t, OU[i], color="blue", alpha=0.8, linewidth=1)

plt.xlabel("Zeit")
plt.ylabel(r"$X(t)$")
plt.title("OU-Prozess (blau) vs. Wiener-Prozess (rot)")

plt.ylim([-10, 10])
plt.grid(True, alpha=0.3)
plt.show()