# -*- coding: utf-8 -*-
"""Regression Klassifikation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p5S9xBmjXpwIPSDlbm9DwZR6vB1RKIl3
"""

import matplotlib.pyplot as plt
import numpy as np

#Regression-Daten
np.random.seed(0)
X_reg = np.linspace(0, 10, 30)
y_reg = 0.5 * X_reg + 1 + np.random.normal(scale=1.0, size=X_reg.shape)

#Lineare Regression fitten
coef = np.polyfit(X_reg, y_reg, 1)
poly1d_fn = np.poly1d(coef)

#Klassifikations-Daten
np.random.seed(1)
X_class1 = np.random.randn(20, 2) + np.array([2, 2])
X_class2 = np.random.randn(20, 2) + np.array([-2, -2])


#Plot erstellen
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

#Regression-Plot
axes[0].scatter(X_reg, y_reg, color="blue", label="Datenpunkte")
axes[0].plot(X_reg, poly1d_fn(X_reg), color="red", label="Regressionslinie")
axes[0].set_title("Regression")
axes[0].set_xlabel("x")
axes[0].set_ylabel("y")
axes[0].legend()

#Klassifikations-Plot
axes[1].scatter(X_class1[:, 0], X_class1[:, 1], color="green", label="Klasse 1")
axes[1].scatter(X_class2[:, 0], X_class2[:, 1], color="orange", label="Klasse 2")

x_line = np.linspace(-5, 5, 100)
y_line = -x_line
axes[1].plot(x_line, y_line, color="red", linestyle="--", label="Entscheidungsgrenze")

axes[1].set_title("Klassifikation")
axes[1].set_xlabel("x")
axes[1].set_ylabel("y")
axes[1].legend()
plt.tight_layout()
plt.show()