# -*- coding: utf-8 -*-
"""Simulation Ornstein-Uhlenbeck Pfaden.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uXDw4uolQY_93_y014XO4Tgck5dJaWbV
"""

import numpy as np
import matplotlib.pyplot as plt

theta, kappa, sigma, X0, T, dt = 0, 1, 0.3, 1, 5, 0.01
n_steps = int(T/dt)
n_paths = 3

t = np.linspace(0, T, n_steps)
paths = np.zeros((n_paths, n_steps))
for i in range(n_paths):
    X = X0
    paths[i, 0] = X0
    for j in range(1, n_steps):
        dW = np.sqrt(dt) * np.random.randn()
        X += -kappa * (X - theta) * dt + sigma * dW
        paths[i, j] = X
plt.plot(t, paths.T)
plt.axhline(theta, color='black', linestyle='--')
plt.title('Simulation von Ornstein-Uhlenbeck-Pfaden')
plt.xlabel('Zeit')
plt.ylabel('X(t)')
plt.show()