# -*- coding: utf-8 -*-
"""CNN-LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Ocwz3Ki-0jCP_-LUv2fxg5UlUPVcWzG
"""

#Multi-Step CNN-LSTM

#Imports & Startkonfiguration

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from tqdm import tqdm

Daten = "Masterarbeit Werte pchip.xlsx"

Variablen = ["Einlagevolumen", "€STR", "Einlagezinssatz"]
Einheiten = {"Einlagevolumen": "Mrd. €", "€STR": "%", "Einlagezinssatz": "%"}

Gedächtnis = 100
Prognosehorizont = 100
Simulationen = 100
Epochs = 20
Batch = 32
Lernrate = 1e-3
Seed = 42 #Für Wiederholbarkeit
HiddenLayer = 64

TrainingEnde = "2025-03-15"
InputAnfang, InputEnde = "2025-03-15", "2025-06-22"
HistorieAnfang, HistorieEnde = "2025-01-01", "2025-06-23" #Für Plot

Device = torch.device("cuda" if torch.cuda.is_available() else "cpu") #Habe Google Colab benutzt (T4 GPU), für schnellere Ergebnisse

np.random.seed(Seed)
torch.manual_seed(Seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(Seed)

#Daten & Sequenzen
#df=Dataframe
df = (
    pd.read_excel(Daten)
      .iloc[1:8280, 0:4]
      .rename(columns={0:"Datum",1:"Einlagevolumen",2:"€STR",3:"Einlagezinssatz"})
)
df["Datum"] = pd.to_datetime(df["Datum"])
df = df.set_index("Datum")

#Skalierung der Zeitreihen auf [0,1]

scaler = MinMaxScaler()
data = scaler.fit_transform(df.values)

#Konstruktion von Input-/Output-Sequenzen für die direkte Multi-Step-Prognose
def Sequenz(x, gd, hz):
    return (
        np.array([x[i:i+gd] for i in range(len(x)-gd-hz+1)]),
        np.array([x[i+gd:i+gd+hz] for i in range(len(x)-gd-hz+1)])
    )
#Trainingssplit
X, y = Sequenz(data, Gedächtnis, Prognosehorizont)
split = df.index.get_loc(TrainingEnde) - (Gedächtnis - 1)

X_Training, y_Training = X[:split], y[:split]

loader = DataLoader(
    TensorDataset(
        torch.tensor(X_Training, dtype=torch.float32),
        torch.tensor(y_Training, dtype=torch.float32)
    ),
    batch_size=Batch,
    shuffle=True
)

#CNN-LSTM-Modell

class CNN_LSTM(nn.Module):
    def __init__(self, hidden=HiddenLayer):
        super().__init__()

        #CNN: lokale zeitliche Muster
        self.cnn = nn.Sequential(
            nn.Conv1d(in_channels=3, out_channels=32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Conv1d(32, 32, kernel_size=3, padding=1),
            nn.ReLU()
        )

        #LSTM auf CNN-Features
        self.lstm = nn.LSTM(
            input_size=32,
            hidden_size=hidden,
            batch_first=True
        )

        #Direkter Multi-Step-Decoder
        self.fc = nn.Linear(hidden, Prognosehorizont * 3)

    def forward(self, x):
        x = x.permute(0, 2, 1)
        x = self.cnn(x)
        x = x.permute(0, 2, 1)

        out, _ = self.lstm(x)
        out = out[:, -1]
        out = self.fc(out)

        return out.view(-1, Prognosehorizont, 3)


def train_model():
    model = CNN_LSTM().to(Device)
    opt = torch.optim.Adam(model.parameters(), lr=Lernrate) #Optimierung mit Adam
    loss_fn = nn.MSELoss()

    model.train()
    for _ in range(Epochs):
        for xb, yb in loader:
            xb, yb = xb.to(Device), yb.to(Device)
            opt.zero_grad()
            loss_fn(model(xb), yb).backward()
            opt.step()
    return model.state_dict()


#Ensemblegenerierung

Modellzustände = [train_model() for _ in tqdm(range(Simulationen), desc="Training Ensemble")]

Modelle = []
for s in Modellzustände:
    m = CNN_LSTM().to(Device)
    m.load_state_dict(s)
    m.eval()
    Modelle.append(m)

I0 = df.index.get_loc(InputAnfang)
I1 = df.index.get_loc(InputEnde) + 1

x_Input = torch.tensor(data[I0:I1], dtype=torch.float32).unsqueeze(0).to(Device)
OriSkal = data[I1:I1+Prognosehorizont]

Vorhersagen = []
with torch.no_grad():
    for m in Modelle:
        Vorhersagen.append(m(x_Input).cpu().numpy()[0])

Vorhersagen = scaler.inverse_transform(
    np.array(Vorhersagen).reshape(-1, 3)
).reshape(Simulationen, Prognosehorizont, 3)

Real = scaler.inverse_transform(OriSkal)

Mittelwert = Vorhersagen.mean(axis=0)
ki90 = np.percentile(Vorhersagen, [5, 95], axis=0)
ki98 = np.percentile(Vorhersagen, [1, 99], axis=0)

#Plot

Historie = df.loc[HistorieAnfang:HistorieEnde]
Historie_inv = Historie.values
x_Zukunft = pd.date_range(HistorieEnde, periods=Prognosehorizont, freq="D")

plt.figure(figsize=(15, 9))

for i, name in enumerate(Variablen):
    ax = plt.subplot(3, 1, i+1)
    ax.plot(Historie.index, Historie_inv[:, i], color="blue", label="Historische Daten")
    ax.plot(x_Zukunft, Mittelwert[:, i], color="red", label="Vorhersage (Mittelwert)")
    ax.fill_between(x_Zukunft, ki90[0,:,i], ki90[1,:,i], color="blue", alpha=0.3, label="90%-KI")
    ax.fill_between(x_Zukunft, ki98[0,:,i], ki98[1,:,i], color="blue", alpha=0.15, label="98%-KI")
    ax.plot(x_Zukunft, Real[:, i], "--", color="black", label="Reale Werte")
    ax.set_ylabel(f"{name} [{Einheiten[name]}]")
    ax.set_title(f"Ensemble ({Simulationen} Simulationen) – {name}")
    ax.grid(True)
    ax.legend()

plt.xlabel("Datum")
plt.tight_layout()
plt.show()