# -*- coding: utf-8 -*-
"""Lévy-driven OU-Prozess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NC6djgYak0kh2vvqefAyv8JmgN5EuRO3
"""

from google.colab import files
uploaded = files.upload()

#Lévy-driven OU-Prozess

#Imports & Startkonfiguration

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from numpy.linalg import lstsq
from scipy.optimize import minimize
from scipy.stats import invgauss
from scipy.special import kve

Daten = "Masterarbeit Werte pchip.xlsx"

Variablen = ["Einlagevolumen", "€STR", "Einlagezinssatz"]
Einheiten = {"Einlagevolumen": "Mrd. €", "€STR": "%", "Einlagezinssatz": "%"}

Simulationen = 1000
Horizont = 100
Seed = 42 #Für Wiederholbarkeit
HistorieAnfang, HistorieEnde = "2025-01-01", "2025-06-23" #Für Plot
np.random.seed(Seed)

#Daten laden

df = pd.read_excel(Daten).iloc[1:8180, 0:4]
df.columns = ["Datum", *Variablen]
df["Datum"] = pd.to_datetime(df["Datum"])
df = df.set_index("Datum").sort_index()


df_fut = pd.read_excel(Daten).iloc[8179:8280, 0:4]
df_fut.columns = ["Datum", *Variablen]
df_fut["Datum"] = pd.to_datetime(df_fut["Datum"])

#Transformationen wie beim Paper "Non-maturing deposits modelling in a Ornstein-Uhlenbeck framework"
#X1 = Marktzins (€STR) in Level-Form
#X2 = Einlagezinssatz als Log-Rate (mit Shift zur Positivität)
#X3 = Logarithmiertes Einlagevolumen

for d in (df, df_fut):
    d["X1"] = d["€STR"]
    d["X3"] = np.log(d["Einlagevolumen"])

min_rate = min(df["Einlagezinssatz"].min(), df_fut["Einlagezinssatz"].min())
Shift = 1e-4 - min_rate if min_rate <= 0 else 0.0

df["X2"] = np.log(df["Einlagezinssatz"] + Shift)
df_fut["X2"] = np.log(df_fut["Einlagezinssatz"] + Shift)

Spalten = ["X1", "X2", "X3"]
Daten_raw = df[Spalten].values


#Normalisierung

Mittel = Daten_raw.mean(axis=0)
Std = Daten_raw.std(axis=0, ddof=0)
Daten_norm = (Daten_raw - Mittel) / Std

#VAR(1)-Schätzung

X = Daten_norm[:-1]
Y = Daten_norm[1:]
T, k = X.shape

a = np.zeros(k)
B = np.zeros((k, k))
Residuen = np.zeros_like(Y)
 #OLS
for i in range(k):
    Xi = np.c_[np.ones(T), X[:, :i+1]]
    bi = lstsq(Xi, Y[:, i], rcond=None)[0]
    a[i], B[i, :i+1] = bi[0], bi[1:]
    Residuen[:, i] = Y[:, i] - Xi @ bi

#Innovationsstruktur

Sigma_u = np.cov(Residuen.T)
L = np.linalg.cholesky(Sigma_u)

sigma = np.diag(L)
S = L / sigma
Eps = Residuen @ np.linalg.inv(S).T

#NIG-Loglikelihood

def nig_nll(param, x, s):
    logg, beta = param

    logg = np.clip(logg, -6.0, 6.0)
    beta = np.clip(beta, -25.0, 25.0)

    gamma = np.exp(logg)
    alpha = np.sqrt(gamma**2 + beta**2)

    s = max(s, 1e-3)

    delta = (s**2) * gamma**3 / alpha**2
    delta = max(delta, 1e-6)

    mu = -delta * beta / gamma

    tau = (x - mu) / delta
    z = alpha * delta * np.sqrt(1 + tau**2)
    z = np.maximum(z, 1e-12)

    logkv = np.log(kve(1, z)) - z

    ll = (
        np.log(alpha / np.pi)
        - np.log(np.sqrt(1 + tau**2))
        + delta * gamma
        + beta * (x - mu)
        + logkv
    )
    return -np.sum(ll)

#NIG-Parameterschätzung

Start = np.zeros(2 * k)
Bounds = [(-10, 10), (-50, 50)] * k

def nll_gesamt(p):
    return sum(
        nig_nll(p[2*i:2*i+2], Eps[:, i], sigma[i])
        for i in range(k)
    )

res = minimize(nll_gesamt, Start, bounds=Bounds, method="L-BFGS-B")
loggamma = res.x[0::2]
beta = res.x[1::2]


#Joint Maximum Likelihood

def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-z))

def logit(x):
    x = np.clip(x, 1e-6, 1.0 - 1e-6)
    return np.log(x / (1.0 - x))


def unpack_theta(p):
    idx = 0

    #Drift
    a_hat = p[idx:idx+3]; idx += 3

    #Diagonale von B (in (0,1))
    b11 = sigmoid(p[idx]); idx += 1
    b22 = sigmoid(p[idx]); idx += 1
    b33 = sigmoid(p[idx]); idx += 1

    CAP_B = 0.6
    CAP_S = 2.0

    #Off-Diagonale von B (Vorzeichenrestriktionen)
    b21 =  CAP_B * sigmoid(p[idx]); idx += 1
    b31 = -CAP_B * sigmoid(p[idx]); idx += 1
    b32 =  CAP_B * sigmoid(p[idx]); idx += 1

    B_hat = np.array([
        [b11, 0.0, 0.0],
        [b21, b22, 0.0],
        [b31, b32, b33]
    ])

    #Innovationsmischung S (Untere Dreiecksmatrix, diag = 1)
    s21 =  CAP_S * sigmoid(p[idx]); idx += 1
    s31 = -CAP_S * sigmoid(p[idx]); idx += 1
    s32 =  CAP_S * sigmoid(p[idx]); idx += 1

    S_hat = np.array([
        [1.0, 0.0, 0.0],
        [s21, 1.0, 0.0],
        [s31, s32, 1.0]
    ])

    sigma_hat = 1e-3 + np.exp(p[idx:idx+3]); idx += 3

    #NIG-Parameter
    loggamma_hat = p[idx:idx+3]; idx += 3
    beta_hat     = p[idx:idx+3]

    return a_hat, B_hat, S_hat, sigma_hat, loggamma_hat, beta_hat


def joint_negloglik(p):
    a_hat, B_hat, S_hat, sigma_hat, loggamma_hat, beta_hat = unpack_theta(p)

    #Innovationsprozess
    U = Y - (a_hat[None, :] + X @ B_hat.T)
    EPS = U @ np.linalg.inv(S_hat).T

    nll = 0.0
    for i in range(3):
        nll += nig_nll(
            [loggamma_hat[i], beta_hat[i]],
            EPS[:, i],
            sigma_hat[i]
        )
    return nll

#Initialwerte aus Step 1 (OLS) und Step 2 (NIG-ML)

p0 = []
p0.extend(a.tolist())

p0.extend([
    logit(B[0,0]),
    logit(B[1,1]),
    logit(B[2,2]),
    np.log(abs(B[1,0]) + 1e-8),
    np.log(abs(B[2,0]) + 1e-8),
    np.log(abs(B[2,1]) + 1e-8),
    np.log(abs(S[1,0]) + 1e-8),
    np.log(abs(S[2,0]) + 1e-8),
    np.log(abs(S[2,1]) + 1e-8)
])

p0.extend(np.log(sigma + 1e-8))
p0.extend(loggamma.tolist())
p0.extend(beta.tolist())

p0 = np.array(p0)

bounds = (
    [(-5, 5)] * 3 +          #a
    [(-10, 10)] * 3 +        #diag(B)
    [(-20, 20)] * 6 +        #off-diag B und S
    [(-20, 20)] * 3 +        #sigma
    [(-10, 10)] * 3 +        #loggamma
    [(-100, 100)] * 3        #beta
)

res3 = minimize(
    joint_negloglik,
    p0,
    method="L-BFGS-B",
    bounds=bounds
)

a, B, S, sigma, loggamma, beta = unpack_theta(res3.x)

#Simulation (Joint-ML-Parameter)


Simulation = np.zeros((Simulationen, Horizont, k))

for s in range(Simulationen):
    x = Daten_norm[-1].copy()
    for t in range(Horizont):
        eps = np.zeros(k)
        for i in range(k):
            g = np.exp(loggamma[i])
            a_i = np.sqrt(g**2 + beta[i]**2)
            d = (sigma[i]**2) * g**3 / a_i**2
            mu = -d * beta[i] / g

            V = invgauss.rvs(1 / (g * d), scale=d**2)
            eps[i] = mu + beta[i] * V + np.sqrt(V) * np.random.randn()

        u = S @ eps
        x = a + B @ x + u
        Simulation[s, t] = x

#Rücktransformation

Sim_trans = Simulation * Std + Mittel
sim_estr = Sim_trans[:, :, 0]
sim_depo = np.exp(Sim_trans[:, :, 1]) - Shift
sim_vol  = np.exp(Sim_trans[:, :, 2])

#Plot

Zukunft = pd.date_range(start=df.index[-1],periods=Horizont,freq="D")

Historie = df.loc[HistorieAnfang:HistorieEnde]
Daten = [
    ("Einlagevolumen", Historie["Einlagevolumen"], sim_vol, df_fut["Einlagevolumen"]),
    ("€STR",           Historie["€STR"],           sim_estr, df_fut["€STR"]),
    ("Einlagezinssatz",Historie["Einlagezinssatz"],sim_depo, df_fut["Einlagezinssatz"])
]

plt.figure(figsize=(15, 9))

for i, (name, hist, sim, real) in enumerate(Daten):
    ax = plt.subplot(3, 1, i + 1)

    mw  = sim.mean(axis=0)
    ki90 = np.percentile(sim, [5, 95], axis=0)
    ki98 = np.percentile(sim, [1, 99], axis=0)

    ax.plot(Historie.index, hist, color="blue", lw=2, label="Historische Daten")
    ax.plot(Zukunft, mw, color="red", lw=2, label="Vorhersage (Mittelwert)")
    ax.fill_between(Zukunft, ki90[0], ki90[1], color="blue", alpha=0.30, label="90%-KI")
    ax.fill_between(Zukunft, ki98[0], ki98[1], color="blue", alpha=0.15, label="98%-KI")
    ax.plot(df_fut["Datum"], real, "--", color="black", lw=2, label="Reale Werte")

    ax.set_ylabel(f"{name} [{Einheiten[name]}]")
    ax.set_title(f"Ensemble ({Simulationen} Simulationen) – {name}")
    ax.grid(True)
    ax.legend()

plt.xlabel("Datum")
plt.tight_layout()
plt.show()