# -*- coding: utf-8 -*-
"""Residuenplot LSTM_LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aywmFTUcniDpD6iGwGazVjR2_F9EsKAR
"""

#Folgende Variablen werden benötigt:
#Modell A
#Mittelwert_A, Real_A, x_Zukunft_A

#Modell B
#Mittelwert_B, Real_B, x_Zukunft_B

import matplotlib.dates as mdates

#Residuen

res_lstm_A = Mittelwert_A - Real_A
res_lstm_B = Mittelwert_B - Real_B

features = [
    ("Einlagevolumen", "Mrd. €"),
    ("€STR", "%"),
    ("Einlagezinssatz", "%")
]

fig, axes = plt.subplots(3, 1, figsize=(18, 8), sharex=True)

for i, (name, unit) in enumerate(features):
    ax = axes[i]

    ax.plot(x_Zukunft_A, res_lstm_A[:, i], color="purple", lw=2, label="Residuum LSTM")
    ax.plot(x_Zukunft_B, res_lstm_B[:, i],   color="darkorange", lw=2,
            label="Residuum Lévy-driven OU-Prozess")

    ax.axhline(0, color="black", lw=1)
    ax.set_title(f"Residuenvergleich – {name}")
    ax.set_ylabel(f"Residuum [{unit}]")
    ax.grid(True)
    ax.legend()

#X-Achse: 1. & 15. beschriftet

dates = pd.DatetimeIndex(x_Zukunft_A)
xticks = pd.to_datetime(
    np.sort(
        np.r_[dates.to_period("M").to_timestamp(),
              dates.to_period("M").to_timestamp() + pd.Timedelta(days=14)]
    )
)
plt.tight_layout()
plt.show()