# -*- coding: utf-8 -*-
"""Residuenplot Levy_Levy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j9qEfwTLRgcaFKy2mT88jA8wJ0wh5hAV
"""

#Folgende Variblen werden benötigt:
#Modell A
#sim_vol_A, sim_estr_A, sim_depo_A, Zukunft_A, df_fut_A

#Modell B
#sim_vol_B, sim_estr_B, sim_depo_B, Zukunft_B, df_fut_B

import matplotlib.dates as mdates

#Residuen
res_ou_A = np.column_stack([
    sim_vol_A.mean(axis=0)   - df_fut_A["Einlagevolumen"].values,
    sim_estr_A.mean(axis=0)  - df_fut_A["€STR"].values,
    sim_depo_A.mean(axis=0)  - df_fut_A["Einlagezinssatz"].values
])

res_ou_B = np.column_stack([
    sim_vol_B.mean(axis=0)   - df_fut_B["Einlagevolumen"].values,
    sim_estr_B.mean(axis=0)  - df_fut_B["€STR"].values,
    sim_depo_B.mean(axis=0)  - df_fut_B["Einlagezinssatz"].values
])

fig, axes = plt.subplots(3, 1, figsize=(18, 8), sharex=True)

features = [
    ("Einlagevolumen", "Mrd. €"),
    ("€STR", "%"),
    ("Einlagezinssatz", "%")
]

for i, (name, unit) in enumerate(features):
    ax = axes[i]
    ax.plot(
        Zukunft_A,
        res_ou_A[:, i],
        color="purple",
        lw=2,
        label="Residuum Lévy-driven OU-Prozess_A"
    )

    ax.plot(
        Zukunft_B,
        res_ou_B[:, i],
        color="darkorange",
        lw=2,
        label="Residuum Lévy-driven OU-Prozess_B"
    )

    ax.axhline(0, color="black", lw=1)

    ax.set_title(f"Residuenvergleich – {name}")
    ax.set_ylabel(f"Residuum [{unit}]")
    ax.grid(True, axis="y")   # nur horizontales Grid
    ax.legend()

#X-Achse: 1. & 15. beschriftet

dates = pd.DatetimeIndex(Zukunft_A)
xticks = pd.to_datetime(
    np.sort(
        np.r_[dates.to_period("M").to_timestamp(),
              dates.to_period("M").to_timestamp() + pd.Timedelta(days=14)]
    )
)
plt.tight_layout()
plt.show()