# -*- coding: utf-8 -*-
"""Residuenplot LSTM_Levy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ahY5SNVopTAReoa_UhhMTJgcPMjhzU8-
"""

import matplotlib.dates as mdates

#Residuen

res_lstm = Mittelwert - Real
res_ou = np.column_stack([
    sim_vol.mean(axis=0)   - df_fut["Einlagevolumen"].values,
    sim_estr.mean(axis=0)  - df_fut["€STR"].values,
    sim_depo.mean(axis=0)  - df_fut["Einlagezinssatz"].values
])

features = [
    ("Einlagevolumen", "Mrd. €"),
    ("€STR", "%"),
    ("Einlagezinssatz", "%")
]

fig, axes = plt.subplots(3, 1, figsize=(18, 8), sharex=True)

for i, (name, unit) in enumerate(features):
    ax = axes[i]

    ax.plot(x_Zukunft, res_lstm[:, i], color="purple", lw=2, label="Residuum LSTM")
    ax.plot(x_Zukunft, res_ou[:, i],   color="darkorange", lw=2,
            label="Residuum Lévy-driven OU-Prozess")

    ax.axhline(0, color="black", lw=1)
    ax.set_title(f"Residuenvergleich – {name}")
    ax.set_ylabel(f"Residuum [{unit}]")
    ax.grid(True)
    ax.legend()

#X-Achse: 1. & 15. beschriftet

dates = pd.DatetimeIndex(x_Zukunft)
xticks = pd.to_datetime(
    np.sort(
        np.r_[dates.to_period("M").to_timestamp(),
              dates.to_period("M").to_timestamp() + pd.Timedelta(days=14)]
    )
)
plt.tight_layout()
plt.show()